[tool.poetry]
name = "multibittrie"
version = "0.1.0"
description = ""
authors = ["aliraee"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
memory-profiler = "^0.61.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
